### ISSUE TITLE
有借鉴一些FDTemplateLayoutCell的效率优化理念吗？

### ISSUE THREAD

**Issue by hongdong** [netyouli/WHC_AutoLayoutKit#1]
看了一下这个库，感觉很棒，不知道有没有借鉴一些FDTemplateLayoutCell的效率优化理念吗？FD的效率貌似挺高的，之前也一直用

**Comment by netyouli** [comment]
FDTemplateLayoutCell 效率优化多少我不知道，我的demo8就是微信朋友圈，动态图文混排，在真机4s上滚动无卡顿你说一行代码布局效率会低吗，关键我这个使用简单

**Comment by huFly** [comment]
1.看了下UIView+WHC_AutoLayout.h,api里并没有一些对view约束管理的方法,如修改(更新约束),删除约束的操作可能我没发现. 2.如果有对约束管理的方法,使用这个能对xib里拉的约束做操作吗? 比如用框架代码对xib里view约束进行修改.以及cell用xib布局好了,使用此框架进行高度计算及缓存可以做到吗?

**Comment by netyouli** [comment]
本自动布局框架会自动识别并删除冲突约束所以不需要更新至于删除移除view从父视图就会删除、cell高度会自动缓存，具体用法请看demo

**Comment by lumiao0113** [comment]
不知道作者有没有做过类似微信的发表说说图片上传的demon。有的话可不可以分享学习一下

**Comment by netyouli** [comment]
https://github.com/netyouli/WHC_CollectionViewFramework
可以参考样式4

**Comment by hongdong** [comment]
。
