### ISSUE TITLE
iphonex safearea

### ISSUE THREAD

**Issue by huangping35** [netyouli/WHC_AutoLayoutKit#11]
这个在最新的ios11的safearea如何？

**Comment by netyouli** [comment]
支持 UILayoutGuide，safearea
请更新最新版本
UILayoutGuide * guide = UILayoutGuide.new;
UIView * view = UIView.new;

guide.whc_LeftSpace(10)
.whc_TopSpaceToView(0, self.view.safeAreaLayoutGuide)
.whc_RightSpace(10)
.whc_Height(30);

view.whc_LeftSpace(10)
.whc_RightSpace(10)
.whc_TopSpaceToView(0, guide)
.whc_Height(50);
