### ISSUE TITLE
在ipad上布局不对

### ISSUE THREAD

**Issue by gdfyj90** [netyouli/WHC_AutoLayoutKit#12]
![image](https://user-images.githubusercontent.com/6669427/35078780-d2435da4-fc3e-11e7-9869-af79254fc43c.png)
代码如下
`UIView *view = [[UIView alloc] init];           
  view.backgroundColor = [UIColor redColor];
  [self.view addSubview:view];
  view.whc_LeftSpace(0).whc_RightSpace(0).whc_TopSpace(0).whc_Height(64);`

**Comment by netyouli** [comment]
请使用最新版本

**Comment by gdfyj90** [comment]
pod的版本是2.8.0.7，还是有问题，直接下载的代码就没问题，是pod那边没有更新吗

**Comment by netyouli** [comment]
发个demo我看看

**Comment by netyouli** [comment]
我这里没有问题的
`_v.backgroundColor = [UIColor redColor];

    _v.whc_LeftSpace(0)
    .whc_RightSpace(0)
    .whc_TopSpaceToView(0, self.view.safeAreaLayoutGuide)
    .whc_Height(100);`
![auto](https://user-images.githubusercontent.com/5723961/35081716-bd0a7b90-fc50-11e7-87a3-dd359a180763.png)
_

**Comment by gdfyj90** [comment]
嗯查到问题了，是自己的基类没写好导致的
