### ISSUE TITLE
类似这样的布局要怎么写

### ISSUE THREAD

**Issue by gdfyj90** [netyouli/WHC_AutoLayoutKit#14]
![photo_2018-02-19_15-27-53](https://user-images.githubusercontent.com/6669427/36366514-78b454a0-1589-11e8-9d71-ae1580d615cc.jpg)
就是扣除间距后，子控件的宽度平均排列。只能用stackview吗

**Comment by hongdong** [comment]
间距约束设好，两个按钮等宽就行了。

**Comment by gdfyj90** [comment]
@hongdong 方便贴一下代码吗

**Comment by netyouli** [comment]
`commitBtn.whc_LeftSpace(20).whc_Height(50).whc_RightSpaceToView(20,resetBtn).whc_Centery(0);`
`resetBtn.whc_RightSpace(20).whc_Height(50).whc_WidthEqualToView(commitBtn).whc_Centery(0);`
