### ISSUE TITLE
是否兼容 masonry？

### ISSUE THREAD

**Issue by dagundejuzi** [netyouli/WHC_AutoLayoutKit#15]
用 masonry 布的局，只在计算行高的时候用到这个框架的 api，是否能正确计算出行高？

另外有个疑问一直解决不了，用SDLayout 、本框架和自己做的计算行高都出现同样的问题。
在计算行高的方法中，基本上是用` [tableView dequeueReusableCellWithIdentifier:CellID]`的方法起获取一个模型 cell，然后给 model 再计算。问题是 获取到的这个 cell 是空，一直都是空，非常奇怪。SDLayout框架中是空就重新创建了 cell，然后导致页面上有叠在一起的 cell。你的似乎可能也是同样的，因为现象一样。这个问题查了好久，好像没人遇到过，没见到有人提这个的。

还有个问题请教下，只由系统来自动计算行高，在 iOS 11上能正常显示，在 ios 10中就变默认的44了，输出的信息来看，iOS 11中不会有 cellContentView.height = 44 这个约束，在 ios 10中就有，代码没动，也没有定高度，都是由子控件去撑开的。

**Comment by dagundejuzi** [comment]
cell 叠一起可能是我布局有问题，但是获取到空就不知道为嘛了。

**Comment by netyouli** [comment]
这库里面的计算cell高度模块可以计算使用任何布局库(frame，masnory等等)，也就是说自动计算cell高度和使用什么布局没有关系的。希望能帮助到你
