### ISSUE TITLE
tabelViewCell的算高方式？

### ISSUE THREAD

**Issue by dagundejuzi** [netyouli/WHC_AutoLayoutKit#16]
RT，是不是获取 cell 最底部的 view，然后用他的maxY (+加上底部间隙)作为 cell 的高度？
但是我在  heightForRowAtIndexPath里，dequeueReusableCellWithIdentifier 获取 cell，给值， layoutIfNeeded ，然后打印 bottomView 的 frame，全是 0。
高度缓存似乎不是一直12345....延续下去保存的，某些时候会删掉一些？
能讲下 cell 的高度是如何计算的，和高度缓存的机制吗？

**Comment by netyouli** [comment]
是通过cell最底部view的maxy来计算，至于frame为0需要强制布局layoutIfNeeded，然后再获取frame就是正常的，高度缓存是根据indexpath来存储到dict里面的这样再滑动的时候通过indexpath去字典里面去对应的高度并返回即可
