### ISSUE TITLE
whc_TopSpaceToView 内存没法释放？dealloc没有走

### ISSUE THREAD

**Issue by sugerGDev** [netyouli/WHC_AutoLayoutKit#18]

**Comment by sugerGDev** [comment]
_accountInputView.whc_LeftSpace(0).whc_RightSpace(0).whc_Height(h).whc_TopSpaceToView(50, self.logoImg);

**Comment by sugerGDev** [comment]
使用方法

**Comment by netyouli** [comment]
这个库不存在对象持有问题

**Comment by sugerGDev** [comment]
可是把这段代码屏蔽掉 dealloc才能走呀

**Comment by sugerGDev** [comment]
iOS 12

**Comment by netyouli** [comment]
发个demo我

**Comment by sugerGDev** [comment]
好，晚上的时候

**Comment by sugerGDev** [comment]
@implementation DemoVC1
- (void)dealloc {
    
}
demo1 中ViewController 没有走dealloc

**Comment by netyouli** [comment]
demo里列表上的demo1对应代码里的不是demo1，是demo7，库没有内存问题的，我试过的
