### ISSUE TITLE
MLeaksFinder检测到内存泄漏，如下图

### ISSUE THREAD

**Issue by GreatLiyi** [netyouli/WHC_AutoLayoutKit#20]
![image](https://user-images.githubusercontent.com/11475531/58140651-9f2aa980-7c72-11e9-9b82-31a085014c6f.png)
![image](https://user-images.githubusercontent.com/11475531/58140713-e9138f80-7c72-11e9-976f-2187c838e52a.png)

**Comment by netyouli** [comment]
这个问题已经修复
