### ISSUE TITLE
使用cell高度的会崩溃

### ISSUE THREAD

**Issue by Flonger** [netyouli/WHC_AutoLayoutKit#4]
使用：
- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath {
    return [UITableViewCell whc_CellHeightForIndexPath:indexPath tableView:tableView];
}

会在下面这里崩溃：
+ (CGFloat)whc_CellHeightForIndexPath:(NSIndexPath *)indexPath tableView:(UITableView *)tableView {}
方法的：
if (tableViewWidth == 0) {
        [tableView layoutIfNeeded]; //崩溃在这里
        tableViewWidth = CGRectGetWidth(tableView.frame);
    }

**Comment by netyouli** [comment]
这个问题你已经私下找我了，是你代码问题
