### ISSUE TITLE
作者使用过SDAutoLayout吗？感觉API和你的很像，原理是不是也一致呢？

### ISSUE THREAD

**Issue by lyb5834** [netyouli/WHC_AutoLayoutKit#5]
RT

**Comment by netyouli** [comment]
SDAutoLayout我看过，他是基于frame布局利用UIView的`- (void)layoutSubviews`高频调用特性来实现自动布局的，而WHC_AutoLayout是基于NSLayoutConstraint开发，所以是本质区别的
