### ISSUE TITLE
最近开始用这个库、发现了几个问题、不知道是不是我使用的姿势不对

### ISSUE THREAD

**Issue by hongdong** [netyouli/WHC_AutoLayoutKit#6]
首先互相不冲突的约束，写的顺序不一样出来的结果居然会不一样，这个很困扰
其次Button的宽度设置一直设置不上去，Button始终是自适应的宽度。

**Comment by netyouli** [comment]
约束和顺序是没有关系的，我建议你参考参考我提供的demo事例，欢迎提问
