### ISSUE TITLE
WHC_AutoLayoutKit_Swift2_3

### ISSUE THREAD

**Issue by MrMessy77** [netyouli/WHC_AutoLayoutKit#7]
使用cocoapods导入pod 'WHC_AutoLayoutKit_Swift2_3', '~> 2.6.5'，无法导入。

**Comment by netyouli** [comment]
可以的，我之前都是测试过的，可能你的本地pod环境没弄好

**Comment by MrMessy77** [comment]
已解决，谢谢。

**Comment by netyouli** [comment]
swift请使用WHC_Layout

**Comment by netyouli** [comment]
WHC_AutoLayoutKit_Swift***将不再维护
